blocks:
- config:
    email: arthursongwa@gmail.com
    imap_host: imap.gmail.com
    max_display: 5
    password: tjug dved epyx xyhw
  enabled: true
  grid_col: 2
  grid_row: 1
  id: emails
- config:
    keywords: Full Stack
    location: France
    max_display: 6
  enabled: true
  grid_col: 1
  grid_row: 0
  id: jobs
- config: {}
  enabled: true
  grid_col: 2
  grid_row: 0
  id: clock
- config:
    language: fr-FR
    tmdb_api_key: 36106a1e92d6b1f55acb2c771c53fa83
  enabled: true
  grid_col: 0
  grid_row: 1
  id: movies
- config:
    api_key: 42509add1cb49a8433a613f1872efc93
    city: Tours
  enabled: true
  grid_col: 1
  grid_row: 1
  id: weather
window:
  always_on_top: true
  height: 750
  opacity: 0.97
  width: 1200
  x: 50
  y: 50
